version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/demo-react-native
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/demo
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/storybook
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/config-eslint
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/config-prettier
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/config-typescript
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/database
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/js-core
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/js
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/lib
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/react-native
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/surveys
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/types
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/vite-plugins
    schedule:
      interval: daily
